{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "58f1f08e-0e43-4a45-9240-eed296a4904a",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- File: databricks/validation/silver_checks.sql\n",
    "-- Purpose: Validate Silver layer table presence, counts, key quality, and referential integrity.\n",
    "\n",
    "-- =========================\n",
    "-- 1) Table existence checks\n",
    "-- =========================\n",
    "SHOW TABLES IN silver;\n",
    "\n",
    "-- =================\n",
    "-- 2) Row count checks\n",
    "-- =================\n",
    "SELECT 'silver.calendar'   AS table_name, COUNT(*) AS row_count FROM silver.calendar\n",
    "UNION ALL\n",
    "SELECT 'silver.customers'  AS table_name, COUNT(*) AS row_count FROM silver.customers\n",
    "UNION ALL\n",
    "SELECT 'silver.products'   AS table_name, COUNT(*) AS row_count FROM silver.products\n",
    "UNION ALL\n",
    "SELECT 'silver.territories' AS table_name, COUNT(*) AS row_count FROM silver.territories\n",
    "UNION ALL\n",
    "SELECT 'silver.fact_sales' AS table_name, COUNT(*) AS row_count FROM silver.fact_sales\n",
    "ORDER BY table_name;\n",
    "\n",
    "-- =====================================\n",
    "-- 3) Null checks on critical fact columns\n",
    "-- =====================================\n",
    "SELECT\n",
    "  SUM(CASE WHEN OrderDate IS NULL THEN 1 ELSE 0 END)      AS null_orderdate,\n",
    "  SUM(CASE WHEN OrderNumber IS NULL THEN 1 ELSE 0 END)    AS null_ordernumber,\n",
    "  SUM(CASE WHEN OrderLineItem IS NULL THEN 1 ELSE 0 END)  AS null_orderlineitem,\n",
    "  SUM(CASE WHEN ProductKey IS NULL THEN 1 ELSE 0 END)     AS null_productkey,\n",
    "  SUM(CASE WHEN CustomerKey IS NULL THEN 1 ELSE 0 END)    AS null_customerkey,\n",
    "  SUM(CASE WHEN TerritoryKey IS NULL THEN 1 ELSE 0 END)   AS null_territorykey\n",
    "FROM silver.fact_sales;\n",
    "\n",
    "-- ==================================\n",
    "-- 4) Duplicate grain check on fact\n",
    "-- Grain: (OrderNumber, OrderLineItem)\n",
    "-- ==================================\n",
    "SELECT COUNT(*) AS duplicate_grain_groups\n",
    "FROM (\n",
    "  SELECT OrderNumber, OrderLineItem, COUNT(*) AS c\n",
    "  FROM silver.fact_sales\n",
    "  GROUP BY OrderNumber, OrderLineItem\n",
    "  HAVING COUNT(*) > 1\n",
    ") d;\n",
    "\n",
    "-- ============================\n",
    "-- 5) Basic business rule checks\n",
    "-- ============================\n",
    "SELECT\n",
    "  SUM(CASE WHEN OrderQuantity <= 0 THEN 1 ELSE 0 END) AS invalid_quantity_rows\n",
    "FROM silver.fact_sales;\n",
    "\n",
    "-- ===========================\n",
    "-- 6) Date coverage check (fact)\n",
    "-- ===========================\n",
    "SELECT\n",
    "  MIN(OrderDate) AS min_order_date,\n",
    "  MAX(OrderDate) AS max_order_date\n",
    "FROM silver.fact_sales;\n",
    "\n",
    "-- ==========================================\n",
    "-- 7) Referential integrity checks from fact\n",
    "-- ==========================================\n",
    "\n",
    "-- Missing CustomerKey in silver.customers\n",
    "SELECT COUNT(*) AS missing_customers\n",
    "FROM silver.fact_sales f\n",
    "LEFT JOIN silver.customers c\n",
    "  ON f.CustomerKey = c.CustomerKey\n",
    "WHERE c.CustomerKey IS NULL;\n",
    "\n",
    "-- Missing ProductKey in silver.products\n",
    "SELECT COUNT(*) AS missing_products\n",
    "FROM silver.fact_sales f\n",
    "LEFT JOIN silver.products p\n",
    "  ON f.ProductKey = p.ProductKey\n",
    "WHERE p.ProductKey IS NULL;\n",
    "\n",
    "-- Missing TerritoryKey in silver.territories (territory dim uses SalesTerritoryKey)\n",
    "SELECT COUNT(*) AS missing_territories\n",
    "FROM silver.fact_sales f\n",
    "LEFT JOIN silver.territories t\n",
    "  ON f.TerritoryKey = t.SalesTerritoryKey\n",
    "WHERE t.SalesTerritoryKey IS NULL;\n",
    "\n",
    "-- Missing OrderDate in silver.calendar\n",
    "SELECT COUNT(*) AS missing_dates\n",
    "FROM silver.fact_sales f\n",
    "LEFT JOIN silver.calendar d\n",
    "  ON f.OrderDate = d.Date\n",
    "WHERE d.Date IS NULL;\n",
    "\n",
    "-- ========================================\n",
    "-- 8) Optional expected-count sanity checks\n",
    "-- ========================================\n",
    "-- Update expected values if source changes.\n",
    "SELECT\n",
    "  CASE WHEN (SELECT COUNT(*) FROM silver.calendar) = 912 THEN 'PASS' ELSE 'FAIL' END AS calendar_count_check,\n",
    "  CASE WHEN (SELECT COUNT(*) FROM silver.customers) = 18148 THEN 'PASS' ELSE 'FAIL' END AS customers_count_check,\n",
    "  CASE WHEN (SELECT COUNT(*) FROM silver.products) = 293 THEN 'PASS' ELSE 'FAIL' END AS products_count_check,\n",
    "  CASE WHEN (SELECT COUNT(*) FROM silver.territories) = 10 THEN 'PASS' ELSE 'FAIL' END AS territories_count_check,\n",
    "  CASE WHEN (SELECT COUNT(*) FROM silver.fact_sales) = 56046 THEN 'PASS' ELSE 'FAIL' END AS fact_count_check;\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "4"
   },
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {},
   "notebookName": "silver_checks.sql",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
